name: Pull

on:
    pull_request:

permissions:
    contents: read
    pull-requests: write

concurrency:
    group: pull-${{ github.ref }}
    cancel-in-progress: true

jobs:
    pre-commit:
        name: Run pre-commit
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@v7
              with:
                  fetch-depth: 0
                  fetch-tags: true

            - name: Setup JDK 21
              uses: actions/setup-java@v6
              with:
                  java-version: "21"
                  distribution: "temurin"

            - name: Setup Python
              uses: actions/setup-python@v7
              with:
                  python-version: "3.x"

            - name: Setup Gradle
              uses: gradle/actions/setup-gradle@v6
              with:
                  gradle-version: "wrapper"

            - name: Make Gradle wrapper executable
              run: chmod +x ./gradlew

            - uses: pre-commit-ci/lite-action@v1.1.0
              if: always()
